[project]
name = "shuttlevision"
version = "0.1.0"
description = "Monocular Badminton 3D Flight Reconstruction & Analysis System"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy>=2.2.6", "opencv-python>=4.12.0.88"]
